### ISSUE TITLE
Why not use `primitive`?

### ISSUE THREAD

**Issue by konsumlamm** [meooow25/samsort#15]
What is your reason for not depending on `primitive` for the array types? Is it just to avoid dependencies?
It would make the interface a bit nicer and also allow you to implement `sortPrimArrayBy` for sorting unboxed arrays of arbitrary primitive types, instead of just `sortIntArrayBy`.

I understand that something like `vector` is too heavy, but `primitive` is rather small and most packages depend on it anyway, directly or indirectly (according to Hackage ~89%).

**Comment by meooow25** [comment]
Yes it is purely to avoid the dependency.

> ...according to Hackage ~89%

Wow that's quite a lot. Even so, there are likely arrays out there not based on `primitive`.  
`array` is one, and it comes with GHC. If someone is using `array`, I want this library to be usable without incurring a dependency on `primitive`.

I agree that it would be nice to have a `sortPrimArrayBy` though. If some definitions from `primitive` make it into `base` (which it feels like they should given the 89% figure!), I am open to updating this library to work with them.

**Comment by meooow25** [comment]
@konsumlamm does that answer the question?
Closing the issue since I don't plan to depend on `primitive`, but feel free to leave comments below.
